
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'tangentkyle/node-test'
  dockerId: 'tangentkyle'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
- script: docker login -u $(dockerId) -p $(pswd)
- script: docker push $(imageName)
- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.SourcesDirectory)
    contents: '**/nodeapp.yaml' 
    targetFolder: $(Build.ArtifactStagingDirectory)
    overWrite: true
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop' 
  displayName: 'docker build'

